name: Java13

on:
  push:
    paths:
      - '*/*/java13.yml'
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '5 */3 * * *'
      
jobs:
  java13:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2016]
        update: [x, 4, 3, 2, 1, 0]
      fail-fast: false
      max-parallel: 6
    name: JDK 13.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.${{ matrix.update }}
    - name: java -version
      run: java -version
