name: JavaLatestUpdateForVersion-params

on:
  push:
    paths:
      - '*/*/latestJdkUpdates.yml'

jobs:
  JavaLatestUpdateForVersion_with_params:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2016]
        version: [6, 7, 8, 9, 10, 11, 12, 13, 14, x]
        package: [jre, jdk, jdk+fx]
        arch: [x64, x86]
        exclude:
          - os: macOS-latest
            version: 6
          - os: macOS-latest
            arch: x86
          - package: jdk+fx
            version: [6, 7, 9, 10, 12]
      fail-fast: false
      max-parallel: 5
    name: JDK ${{ matrix.version }}, ${{ matrix.package }}, ${{ matrix.os }}, ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v2
    - name: Download Java from Azul
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.version }}
        java-package: ${{ matrix.package }}
        architecture: ${{ matrix.arch }}
    - name: Check Java Install with get version
      run: java -version
